# fly.toml file generated for pierestore on 2022-12-21T00:45:40+01:00

app = "pierestore"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "mrpier9/restore:latest"

[env]
  ASPNETCORE_URL="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51MGJQyDPcKejRK1OscNPf6yGtx7AKk3hTXwVtFM6BmTe9M9BuKGvXqZMlA5CMW7eKrnP9xTqcLsx3PyN7yEjYzc700ccY6rwhY"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
